# Generated by Django 4.0.5 on 2022-07-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=3)),
                ('description', models.TextField(default='Add a description for this Alliance')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(blank=True, help_text='Define now.gg url for this game', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('battle_power', models.PositiveBigIntegerField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.alliance')),
                ('event_planning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alliance.eventplanning')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.game')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(default='Add a description for this Event')),
                ('pub_date', models.DateTimeField()),
                ('event_planning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alliance.eventplanning')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.game')),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='event_planning',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alliance.eventplanning'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.instance'),
        ),
    ]
